NIFTY50 = [
    "RELIANCE","TCS","INFY","HDFCBANK","ICICIBANK","ITC","LT","SBIN",
    "HCLTECH","AXISBANK","MARUTI","BAJFINANCE","WIPRO","ONGC",
    "SUNPHARMA","NTPC","POWERGRID","ULTRACEMCO","ADANIENT","TITAN",
    "NESTLEIND","KOTAKBANK","BAJAJFINSV","ASIANPAINT","HINDUNILVR",
    "BHARTIARTL","JSWSTEEL","COALINDIA","INDUSINDBK","HDFCLIFE",
    "TATAMOTORS","TECHM","DRREDDY","GRASIM","CIPLA","HEROMOTOCO",
    "EICHERMOT","DIVISLAB","APOLLOHOSP","BRITANNIA","SBILIFE",
    "TATASTEEL","UPL","BAJAJ-AUTO","SHREECEM","HINDALCO",
    "ADANIPORTS","ICICIPRULI"
]