NIFTY50 = [
    "KOTAKBANK", "RELIANCE", "HDFCBANK", "ADANIENT", "BHARTIARTL",
    "ICICIBANK", "AXISBANK", "MARUTI", "ADANIPORTS", "SBIN",
    "ETERNAL", "BAJAJ-AUTO", "M&M", "BAJFINANCE", "LT", "ITC",
    "INFY", "HINDUNILVR", "TCS", "SUNPHARMA", "BEL", "COALINDIA",
    "TMPV", "EICHERMOT", "SHRIRAMFIN", "HINDALCO", "TATASTEEL",
    "ULTRACEMCO", "ONGC", "SBILIFE", "INDIGO", "JIOFIN", "HCLTECH",
    "DRREDDY", "TITAN", "POWERGRID", "BAJAJFINSV", "APOLLOHOSP",
    "MAXHEALTH", "NESTLEIND", "NTPC", "JSWSTEEL", "TRENT",
    "ASIANPAINT", "WIPRO", "GRASIM", "TECHM", "HDFCLIFE",
    "TATACONSUM", "CIPLA"
]
